### ISSUE TITLE
Issue running examples/adaptive_reach.py

### ISSUE THREAD

**Issue by hayday100** [abr/abr_jaco2#27]
```
$ python adaptive_reach.py 
Traceback (most recent call last):
  File "adaptive_reach.py", line 40, in <module>
    path = path_planners.SecondOrderFilter(
AttributeError: module 'abr_control.controllers.path_planners' has no attribute 'SecondOrderFilter'
```
The same error appears when running position_and_orientation_control_osc.py

**Comment by hayday100** [comment]
There is problem with another example too.
```
$ python hand_control.py 
Using Force Command 0x200: 512
ERROR: A while Initializing
INFO: Connection successful
Segmentation fault
```

**Comment by p3jawors** [comment]
Hi @hayday100 ,

Thanks for catching this, I had updated the path planning in abr_control and haven't gotten around to updating the jaco2 repo. I won't be able to update it for a few weeks, but you can go to [this older commit](a248ec56166f01791857a766ac58ee0920c0861c) in `abr_control`, before the path planning was updated, it should work. However, I won't be able to setup the jaco2 to test this out at the moment. Just a note, this repo is for running on an actual jaco2 arm, if you are looking for a simulation, then you can use the `abr_control` repo.

The other issues you are seeing with the `Segmentation Fault` happen when the jaco fails during the process of switching to force control mode. You just need to power cycle the arm to clear the error.

Let me know if you still have issues. I'll leave this open until I get a chance to update the repo.

Cheers,

Pawel

**Comment by hayday100** [comment]
I switched to the oldest pytest_M branch in abr_control and the error changes to:
```
python adaptive_reach.py 

pydmps library required, see github.com/studywolf/pydmps

Generating inertia matrix function
Traceback (most recent call last):
  File "adaptive_reach.py", line 49, in <module>
    ctrlr.generate(zeros, zeros, zeros)
  File "/data/nengo/abr_control/abr_control/controllers/osc.py", line 222, in generate
    M = self.robot_config.M(q)  # inertia matrix in joint space
  File "/data/nengo/abr_control/abr_control/arms/base_config.py", line 290, in M
    self._M = self._calc_M()
  File "/data/nengo/abr_control/abr_control/arms/base_config.py", line 705, in _calc_M
    X = [plucker_transform(
  File "/data/nengo/abr_control/abr_control/arms/base_config.py", line 706, in <listcomp>
    R=eval('self.Tj%il%ia' % (ii, ii+1))[:3, :3],
  File "<string>", line 1, in <module>
AttributeError: 'Config' object has no attribute 'Tj5l6a'
```

**Comment by p3jawors** [comment]
Sorry, I guess  should have waited to get some coffee first as I linked to the commit hash, not the link itself. I've updated the link :sweat_smile: above, and for reference the commit hash is a248ec56166f01791857a766ac58ee0920c0861c

**Comment by p3jawors** [comment]
Closing due to inactivity.
